name: 24/7 Shorts Feed Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install yt-dlp

      - name: Download Video
        run: |
          yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4" "https://drive.google.com/uc?export=download&id=1OFKIBggSKZUyJsuniPz0H6Tl-kgkoSEm" -o video.mp4

      - name: Start Streaming
        run: |
          ffmpeg -fflags +genpts -stream_loop -1 -re -i video.mp4 \
          -vf "crop=ih*9/16:ih,scale=720:1280" \
          -c:v libx264 -preset veryfast -b:v 2000k -maxrate 2000k -bufsize 4000k \
          -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmps://a.rtmp.youtube.com:443/live2/${{ secrets.STREAM_KEY }}"
